### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by ghost** [himank/K-Means#1]
hey, can you let me know the input format for the data and the centroid with an example?

**Comment by liptiavenica** [comment]
let me know the input format, pleaseeeee..

**Comment by JagDhruv** [comment]
@himank plz tell the format of the input data set?

**Comment by JagDhruv** [comment]
@ghost can you tell me the format of the input dataset ?

**Comment by himank** [comment]
Guys, my bad for replying late.

For Centroid, this should be fine:
20.0
30.0
40.0

For data something like this simple should work:
20
23
19
29
33
29
43
35
18
25
27
